import React, { useState } from 'react';
import { useNavigate, useLocation, Navigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import NewProjectModal from './NewProjectModal';
import './ResultsPage.css';

function ResultsPage({ user }) {
  const navigate = useNavigate();
  const location = useLocation();
  const { results, code, language, project, analysisId, viewOnly } = location.state || {};
  const [showCode, setShowCode] = useState(false);
  const [showNewProjectModal, setShowNewProjectModal] = useState(false);

  // Redirect if no results
  if (!results) {
    return <Navigate to="/app" replace />;
  }

  const getScoreColor = (score) => {
    if (score >= 80) return '#10b981';
    if (score >= 60) return '#f59e0b';
    return '#ef4444';
  };

  const getScoreLabel = (score) => {
    if (score >= 90) return 'Excellent';
    if (score >= 80) return 'Good';
    if (score >= 70) return 'Decent';
    if (score >= 60) return 'Fair';
    return 'Needs Work';
  };

  const getSeverityColor = (severity) => {
    switch (severity?.toLowerCase()) {
      case 'high':
      case 'critical':
        return '#ef4444';
      case 'medium':
        return '#f59e0b';
      case 'low':
        return '#10b981';
      default:
        return '#888';
    }
  };

  const handleNewAnalysis = () => {
    // Show modal to create new project for new analysis
    setShowNewProjectModal(true);
  };

  const handleProjectCreated = (newProject) => {
    // Navigate to code analysis page with new project
    navigate('/app', { state: { project: newProject } });
  };

  const handleBackToHome = () => {
    navigate('/home');
  };

  const handleDownloadReport = () => {
    // Generate report content
    const reportDate = new Date().toLocaleString();
    const projectName = project?.name || 'Code Analysis';

    let reportContent = `
================================================================================
                         LOGICGUARD CODE ANALYSIS REPORT
================================================================================

Project: ${projectName}
Language: ${language}
Date: ${reportDate}
Score: ${results.score}/100 (${getScoreLabel(results.score)})

--------------------------------------------------------------------------------
                                   SUMMARY
--------------------------------------------------------------------------------
${results.summary}

`;

    // Add Issues section
    if (results.bugs && results.bugs.length > 0) {
      reportContent += `
--------------------------------------------------------------------------------
                              ISSUES FOUND (${results.bugs.length})
--------------------------------------------------------------------------------
`;
      results.bugs.forEach((bug, index) => {
        reportContent += `
${index + 1}. [${bug.severity?.toUpperCase() || 'ISSUE'}] ${bug.title || bug.type}
   ${bug.line ? `Line: ${bug.line}` : ''}
   Description: ${bug.description}
   ${bug.suggestion ? `Suggestion: ${bug.suggestion}` : ''}
`;
      });
    }

    // Add Optimizations section
    if (results.optimizations && results.optimizations.length > 0) {
      reportContent += `
--------------------------------------------------------------------------------
                        OPTIMIZATION SUGGESTIONS (${results.optimizations.length})
--------------------------------------------------------------------------------
`;
      results.optimizations.forEach((opt, index) => {
        reportContent += `
${index + 1}. ${opt.title}
   ${opt.category ? `Category: ${opt.category}` : ''}
   ${opt.description}
   ${opt.example ? `Example:\n   ${opt.example}` : ''}
`;
      });
    }

    // Add Positives section
    if (results.positives && results.positives.length > 0) {
      reportContent += `
--------------------------------------------------------------------------------
                           WHAT YOU DID WELL (${results.positives.length})
--------------------------------------------------------------------------------
`;
      results.positives.forEach((positive, index) => {
        const text = typeof positive === 'string' ? positive : positive.description;
        reportContent += `${index + 1}. ${text}\n`;
      });
    }

    // Add Code section
    if (code) {
      reportContent += `
--------------------------------------------------------------------------------
                               ANALYZED CODE
--------------------------------------------------------------------------------
${code}
`;
    }

    reportContent += `
================================================================================
                    Generated by LogicGuard - AI-Powered Code Analysis
================================================================================
`;

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `LogicGuard_Report_${projectName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="results-page">
      {/* Header */}
      <header className="results-header">
        <div className="header-left">
          <button className="back-btn" onClick={handleNewAnalysis}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 5v14M5 12h14" />
            </svg>
            New Analysis
          </button>
        </div>
        <div className="header-center">
          <div className="logo-small">
            <img src="/logo.png" alt="LogicGuard" className="logo-img" />
            <span>LogicGuard</span>
          </div>
        </div>
        <div className="header-right">
          <button className="home-btn" onClick={handleBackToHome}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
              <polyline points="9,22 9,12 15,12 15,22" />
            </svg>
            Home
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="results-main">
        <div className="results-container">
          {/* Step Indicator */}
          <div className="step-indicator">
            <div className="step completed">
              <div className="step-number">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                  <polyline points="20,6 9,17 4,12" />
                </svg>
              </div>
              <span>Enter Code</span>
            </div>
            <div className="step-line completed"></div>
            <div className="step active">
              <div className="step-number">2</div>
              <span>View Results</span>
            </div>
          </div>

          {/* Title */}
          <motion.div
            className="results-title"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h1>{viewOnly ? 'Saved Analysis' : 'Analysis Complete'}</h1>
            <p>Here's what LogicGuard found in your {language} code.</p>
            {(results.analysis_id || analysisId) && !viewOnly && (
              <div className="saved-indicator">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                  <polyline points="22,4 12,14.01 9,11.01" />
                </svg>
                Saved to History
              </div>
            )}
          </motion.div>

          {/* View Code Button */}
          {code && (
            <motion.div
              className="view-code-section"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.15 }}
            >
              <button
                className="view-code-btn"
                onClick={() => setShowCode(!showCode)}
              >
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="16,18 22,12 16,6" />
                  <polyline points="8,6 2,12 8,18" />
                </svg>
                {showCode ? 'Hide Code' : 'View Code'}
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  className={`chevron ${showCode ? 'open' : ''}`}
                >
                  <polyline points="6,9 12,15 18,9" />
                </svg>
              </button>

              <AnimatePresence>
                {showCode && (
                  <motion.div
                    className="code-preview-container"
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <div className="code-preview-header">
                      <span className="code-language">{language}</span>
                      <span className="code-lines">{code.split('\n').length} lines</span>
                    </div>
                    <pre className="code-preview">
                      <code>{code}</code>
                    </pre>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}

          {/* Score Card */}
          <motion.div
            className="score-card"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <div className="score-circle" style={{ borderColor: getScoreColor(results.score) }}>
              <span className="score-value" style={{ color: getScoreColor(results.score) }}>
                {results.score}
              </span>
              <span className="score-max">/100</span>
            </div>
            <div className="score-details">
              <span className="score-label" style={{ color: getScoreColor(results.score) }}>
                {getScoreLabel(results.score)}
              </span>
              <p className="score-summary">{results.summary}</p>
            </div>
          </motion.div>

          {/* Metrics */}
          {results.metrics && (
            <motion.div
              className="metrics-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
            >
              <h3>Code Metrics</h3>
              <div className="metrics-grid">
                {Object.entries(results.metrics).map(([key, value]) => (
                  <div key={key} className="metric-item">
                    <span className="metric-label">{key.replace(/_/g, ' ')}</span>
                    <div className="metric-bar-container">
                      <div
                        className="metric-bar-fill"
                        style={{ width: `${Math.min(value, 100)}%` }}
                      ></div>
                    </div>
                    <span className="metric-value">{value}%</span>
                  </div>
                ))}
              </div>
            </motion.div>
          )}

          {/* Bugs Section */}
          {results.bugs && results.bugs.length > 0 && (
            <motion.div
              className="section-card bugs-section"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
            >
              <h3>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10" />
                  <path d="M12 8v4M12 16h.01" />
                </svg>
                Issues Found ({results.bugs.length})
              </h3>
              <div className="bugs-list">
                {results.bugs.map((bug, index) => (
                  <motion.div
                    key={index}
                    className="bug-item"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3, delay: 0.4 + index * 0.1 }}
                  >
                    <div className="bug-header">
                      <span
                        className="severity-badge"
                        style={{ background: getSeverityColor(bug.severity) }}
                      >
                        {bug.severity || 'Issue'}
                      </span>
                      <span className="bug-title">{bug.title || bug.type}</span>
                      {bug.line && <span className="bug-line">Line {bug.line}</span>}
                    </div>
                    <p className="bug-description">{bug.description}</p>
                    {bug.suggestion && (
                      <div className="bug-suggestion">
                        <strong>Suggestion:</strong> {bug.suggestion}
                      </div>
                    )}
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}

          {/* Optimizations Section */}
          {results.optimizations && results.optimizations.length > 0 && (
            <motion.div
              className="section-card optimizations-section"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
            >
              <h3>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polygon points="13,2 3,14 12,14 11,22 21,10 12,10 13,2" />
                </svg>
                Optimization Suggestions ({results.optimizations.length})
              </h3>
              <div className="optimizations-list">
                {results.optimizations.map((opt, index) => (
                  <motion.div
                    key={index}
                    className="optimization-item"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3, delay: 0.5 + index * 0.1 }}
                  >
                    {opt.category && (
                      <span className="category-badge">{opt.category}</span>
                    )}
                    <h4>{opt.title}</h4>
                    <p>{opt.description}</p>
                    {opt.example && (
                      <div className="code-example">
                        <pre>{opt.example}</pre>
                      </div>
                    )}
                  </motion.div>
                ))}
              </div>
            </motion.div>
          )}

          {/* Positives Section */}
          {results.positives && results.positives.length > 0 && (
            <motion.div
              className="section-card positives-section"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.5 }}
            >
              <h3>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
                  <polyline points="22,4 12,14.01 9,11.01" />
                </svg>
                What You Did Well ({results.positives.length})
              </h3>
              <ul className="positives-list">
                {results.positives.map((positive, index) => (
                  <motion.li
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3, delay: 0.6 + index * 0.1 }}
                  >
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                      <polyline points="20,6 9,17 4,12" />
                    </svg>
                    {typeof positive === 'string' ? positive : positive.description}
                  </motion.li>
                ))}
              </ul>
            </motion.div>
          )}

          {/* Action Buttons */}
          <motion.div
            className="results-actions"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.6 }}
          >
            <button className="btn-secondary" onClick={handleBackToHome}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
                <polyline points="9,22 9,12 15,12 15,22" />
              </svg>
              Back to Home
            </button>
            <button className="btn-primary" onClick={handleDownloadReport}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7,10 12,15 17,10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download Report
            </button>
          </motion.div>
        </div>
      </main>

      {/* Footer */}
      <footer className="results-footer">
        <p>LogicGuard - AI-Powered Code Analysis</p>
      </footer>

      {/* New Project Modal */}
      <NewProjectModal
        isOpen={showNewProjectModal}
        onClose={() => setShowNewProjectModal(false)}
        onProjectCreated={handleProjectCreated}
        userId={user?.id}
      />
    </div>
  );
}

export default ResultsPage;
